version: '3.1'

services:
#servicios
  reverse-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: Reverse-Proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - storage/volumes/nginx/certs:/etc/nginx/certs:ro
      - storage/volumes/nginx/vhostd:/etc/nginx/vhost.d
      - sstorage/volumes/nginx/config/settings.conf:/etc/nginx/conf.d/custom_settings.conf:ro
      - storage/var/run/docker.sock:/tmp/docker.sock:ro

  portal:
    image: nginx
    container_name: Portal
    restart: always
    environment:
     - VIRTUAL_HOST=portal-falecogra.hopto.org

    volumes:
      - /storage/www/portal:/usr/share/nginx/html:ro

  erp:
    image: httpd
    container_name: ERP
    restart: always
    environment:
      - VIRTUAL_HOST=erp-falecogra.hopto.org
    volumes:
      - /storage/www/erp:/usr/local/apache2/htdocs