version: '3.1'

services:
#servicios
  reverse-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: Reverse-Proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
     - VIRTUAL_HOST=apps-falecogra.hopto.org #modificar"
    volumes:
      - /volumes/nginx/certs:/etc/nginx/certs:ro
      - /volumes/nginx/vhostd:/etc/nginx/vhost.d
      - /volumes/nginx/config/settings.conf:/etc/nginx/conf.d/custom_settings.conf:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

  portal:
    image: nginx
    container_name: Portal
    restart: always
    #environment:
    # - VIRTUAL_HOST=portal-falecogra.hopto.org #modificar"

    volumes:
      - /volumes/www/portal:/usr/share/nginx/html:ro

  factura:
    image: nginx
    container_name: Factura
    restart: always
    #environment:
      #- VIRTUAL_HOST=erp-falecogra.hopto.org
    volumes:
      - /volumes/www/factura:/usr/share/nginx/html:ro

  erp:
    image: httpd
    container_name: ERP
    restart: always
    #environment:
      #- VIRTUAL_HOST=erp-falecogra.hopto.org
    volumes:
      - /volumes/www/erp:/usr/local/apache2/htdocs